/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AchievementRouteImport } from './routes/achievement'
import { Route as TeamGearRouteImport } from './routes/team-gear'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)

const AchievementRoute = AchievementRouteImport.update({
  id: '/achievement',
  path: '/achievement',
  getParentRoute: () => rootRouteImport,
} as any)

const TeamGearRoute = TeamGearRouteImport.update({
  id: '/team-gear',
  path: '/team-gear',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievement': typeof AchievementRoute
  '/team-gear': typeof TeamGearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievement': typeof AchievementRoute
  '/team-gear': typeof TeamGearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievement': typeof AchievementRoute
  '/team-gear': typeof TeamGearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/achievement' | '/team-gear'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/achievement' | '/team-gear'
  id: '__root__' | '/' | '/about' | '/achievement' | '/team-gear'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementRoute: typeof AchievementRoute
  TeamGearRoute: typeof TeamGearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievement': {
      id: '/achievement'
      path: '/achievement'
      fullPath: '/achievement'
      preLoaderRoute: typeof AchievementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-gear': {
      id: '/team-gear'
      path: '/team-gear'
      fullPath: '/team-gear'
      preLoaderRoute: typeof TeamGearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementRoute: AchievementRoute,
  TeamGearRoute: TeamGearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
